<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FFmpeg.AutoGen" Version="7.1.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MiCamera.Net.Abstractions\MiCamera.Net.Abstractions.csproj" />
    <ProjectReference Include="..\MiCamera.Net.RTSP.Abstractions\MiCamera.Net.RTSP.Abstractions.csproj" />
  </ItemGroup>

</Project>
