<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MiCamera.Net.Abstractions\MiCamera.Net.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\MiCamera.Net\MiCamera.Net.csproj" />
    <ProjectReference Include="..\..\src\rtsp\MiCamera.Net.RTSP\MiCamera.Net.RTSP.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Configs\MiCameraConfig.json" Condition="Exists('Configs\MiCameraConfig.json')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
